---
- name: Create Azure Resource Group
  hosts: localhost
  tasks:
    - name: Create resource group using Azure CLI
      shell: az group create --name myResourceGroup --location eastus
      register: output

    - name: Display output
      debug:
        var: output.stdout

