---
- name: Create Azure Resource Group
  hosts: all
  roles:
    - azcli
  vars:
    azcli_version: 2.60.0
  tasks:
    - name: Create resource group using Azure CLI
      shell: az group create --name myResourceGroup --location eastus
      register: output

    - name: Display output
      debug:
        var: output.stdout

