---
- name: test ansible connection
  hosts: localhost
  connection: localhost
  become: falso
  gather_facts: false
  tasks:
  - name: create resource group
    azure_rm_deployment:
	  resource_group_name: testresourcegroupfromawx
	  location: westus
