---
- name: test ansible connection
  hosts: localhost
  connection: localhost
  become: true
  become_user: root
  gather_facts: false
  tasks:
  - name: create resource group
    azure_rm_resourcegroup:
      name: vinodh
      location: westus
